/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface I18nLocalizable {
        "i18nComponent": string;
        "i18nKey": string;
        "i18nLang": string;
    }
    interface MyComponent {
        "i18nComponent": string;
        "i18nKey": string;
        "i18nLang": string;
    }
    interface TestNoMixing {
        "i18nLang": string;
    }
    interface TestTranslation2 {
        "i18nComponent": string;
        "i18nKey": string;
        "i18nLang": string;
    }
}
declare global {
    interface HTMLI18nLocalizableElement extends Components.I18nLocalizable, HTMLStencilElement {
    }
    var HTMLI18nLocalizableElement: {
        prototype: HTMLI18nLocalizableElement;
        new (): HTMLI18nLocalizableElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTestNoMixingElement extends Components.TestNoMixing, HTMLStencilElement {
    }
    var HTMLTestNoMixingElement: {
        prototype: HTMLTestNoMixingElement;
        new (): HTMLTestNoMixingElement;
    };
    interface HTMLTestTranslation2Element extends Components.TestTranslation2, HTMLStencilElement {
    }
    var HTMLTestTranslation2Element: {
        prototype: HTMLTestTranslation2Element;
        new (): HTMLTestTranslation2Element;
    };
    interface HTMLElementTagNameMap {
        "i18n-localizable": HTMLI18nLocalizableElement;
        "my-component": HTMLMyComponentElement;
        "test-no-mixing": HTMLTestNoMixingElement;
        "test-translation-2": HTMLTestTranslation2Element;
    }
}
declare namespace LocalJSX {
    interface I18nLocalizable {
        "i18nComponent"?: string;
        "i18nKey"?: string;
        "i18nLang"?: string;
    }
    interface MyComponent {
        "i18nComponent"?: string;
        "i18nKey"?: string;
        "i18nLang"?: string;
    }
    interface TestNoMixing {
        "i18nLang"?: string;
    }
    interface TestTranslation2 {
        "i18nComponent"?: string;
        "i18nKey"?: string;
        "i18nLang"?: string;
    }
    interface IntrinsicElements {
        "i18n-localizable": I18nLocalizable;
        "my-component": MyComponent;
        "test-no-mixing": TestNoMixing;
        "test-translation-2": TestTranslation2;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "i18n-localizable": LocalJSX.I18nLocalizable & JSXBase.HTMLAttributes<HTMLI18nLocalizableElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "test-no-mixing": LocalJSX.TestNoMixing & JSXBase.HTMLAttributes<HTMLTestNoMixingElement>;
            "test-translation-2": LocalJSX.TestTranslation2 & JSXBase.HTMLAttributes<HTMLTestTranslation2Element>;
        }
    }
}
