/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface I18nLocalizable {
        "config": any;
        "langKey": string;
        "language": string;
    }
    interface MyComponent {
        "config": any;
        /**
          * The first name
         */
        "first": string;
        "langKey": string;
        "language": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLI18nLocalizableElement extends Components.I18nLocalizable, HTMLStencilElement {
    }
    var HTMLI18nLocalizableElement: {
        prototype: HTMLI18nLocalizableElement;
        new (): HTMLI18nLocalizableElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "i18n-localizable": HTMLI18nLocalizableElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface I18nLocalizable {
        "config"?: any;
        "langKey"?: string;
        "language"?: string;
    }
    interface MyComponent {
        "config"?: any;
        /**
          * The first name
         */
        "first"?: string;
        "langKey"?: string;
        "language"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "i18n-localizable": I18nLocalizable;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "i18n-localizable": LocalJSX.I18nLocalizable & JSXBase.HTMLAttributes<HTMLI18nLocalizableElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
